-- Blacktop OSM country import staging table and merge.
--
-- Use this for new OpenStreetMap court CSV files generated by:
-- scripts/osm_geojson_to_supabase_csv.mjs
--
-- Do not import new country/city OSM CSVs directly into public.courts.
-- Import them into public.courts_osm_import_staging first, inspect them,
-- then run the merge section at the bottom.

create extension if not exists postgis with schema extensions;

drop table if exists public.courts_osm_import_staging;

create table public.courts_osm_import_staging (
  staging_row_id bigserial primary key,
  id text not null,
  name text not null,
  area text not null default 'Unknown area',
  city text not null default 'Unknown city',
  country_code text not null,
  latitude double precision not null,
  longitude double precision not null,
  source text not null default 'openStreetMap',
  source_license text not null default 'ODbL - OpenStreetMap contributors',
  confidence text not null default 'imported',
  last_checked_at text not null default 'Imported',
  court_type text not null default 'unknown',
  access_type text not null default 'unknown',
  price_type text not null default 'unknown',
  has_lights text not null default 'unknown',
  dryness_after_rain text not null default 'unknown',
  slippery_when_wet text not null default 'unknown',
  rain_playable text not null default 'unknown',
  surface_type text not null default 'unknown',
  surface_condition text not null default 'unknown',
  court_cleanliness text not null default 'unknown',
  court_space text not null default 'unknown',
  runoff_safety text not null default 'unknown',
  peak_times text not null default '{unknown}',
  has_nets text not null default 'unknown',
  rim_height text not null default 'unknown',
  rim_type text not null default 'unknown',
  backboard_condition text not null default 'unknown',
  rim_condition text not null default 'unknown',
  hoop_count integer,
  opening_hours text not null default 'Access not confirmed',
  evening_access text not null default 'unknown',
  has_toilets text not null default 'unknown',
  has_drinking_water text not null default 'unknown',
  has_parking text not null default 'unknown',
  has_changing_rooms text not null default 'unknown',
  good_for_solo text not null default 'unknown',
  good_for_pickup text not null default 'unknown',
  good_for_training text not null default 'unknown',
  beginner_friendly text not null default 'unknown',
  notes text not null default '',
  photo_asset_name text,
  photo_url text,
  osm_type text,
  osm_id text,
  osm_ref text,
  osm_tags_json jsonb,
  import_batch text
);

create index if not exists courts_osm_import_staging_id_idx
on public.courts_osm_import_staging (id);

create index if not exists courts_osm_import_staging_country_idx
on public.courts_osm_import_staging (country_code);

-- After creating this table, import your generated CSV into:
-- public.courts_osm_import_staging

-- Preview imported staging rows.
select
  country_code,
  count(*) as staging_rows,
  count(distinct id) as distinct_osm_rows,
  count(*) - count(distinct id) as duplicate_rows_in_staging,
  count(*) filter (where name ilike 'OSM Basketball Court%') as synthetic_names,
  count(*) filter (where latitude is null or longitude is null) as missing_coordinates
from public.courts_osm_import_staging
group by country_code
order by country_code;

-- Preview likely duplicates before merge.
select
  s.id as staging_id,
  s.name as staging_name,
  c.id as existing_id,
  c.name as existing_name,
  round(extensions.st_distance(
    extensions.st_setsrid(extensions.st_makepoint(s.longitude, s.latitude), 4326)::extensions.geography,
    c.location
  )) as distance_m
from public.courts_osm_import_staging s
join public.courts c
  on c.country_code = s.country_code
 and c.location is not null
 and extensions.st_dwithin(
   c.location,
   extensions.st_setsrid(extensions.st_makepoint(s.longitude, s.latitude), 4326)::extensions.geography,
   30
 )
where c.id <> s.id
order by distance_m asc, s.id
limit 100;

-- Merge only rows that are not already present by stable OSM id and are not
-- within 30 metres of an existing court in the same country.
with deduped_staging as (
  select distinct on (id)
    *
  from public.courts_osm_import_staging
  order by id, staging_row_id
)
insert into public.courts (
  id,
  name,
  area,
  city,
  country_code,
  latitude,
  longitude,
  source,
  source_license,
  confidence,
  last_checked_at,
  court_type,
  access_type,
  price_type,
  has_lights,
  dryness_after_rain,
  slippery_when_wet,
  rain_playable,
  surface_type,
  surface_condition,
  court_cleanliness,
  court_space,
  runoff_safety,
  peak_times,
  has_nets,
  rim_height,
  rim_type,
  backboard_condition,
  rim_condition,
  hoop_count,
  opening_hours,
  evening_access,
  has_toilets,
  has_drinking_water,
  has_parking,
  has_changing_rooms,
  good_for_solo,
  good_for_pickup,
  good_for_training,
  beginner_friendly,
  notes,
  photo_asset_name,
  photo_url,
  osm_type,
  osm_id,
  osm_ref,
  osm_tags_json,
  import_batch
)
select
  s.id,
  s.name,
  s.area,
  s.city,
  s.country_code,
  s.latitude,
  s.longitude,
  s.source,
  s.source_license,
  s.confidence,
  s.last_checked_at,
  s.court_type,
  s.access_type,
  s.price_type,
  s.has_lights,
  s.dryness_after_rain,
  s.slippery_when_wet,
  s.rain_playable,
  s.surface_type,
  s.surface_condition,
  s.court_cleanliness,
  s.court_space,
  s.runoff_safety,
  s.peak_times,
  s.has_nets,
  s.rim_height,
  s.rim_type,
  s.backboard_condition,
  s.rim_condition,
  s.hoop_count,
  s.opening_hours,
  s.evening_access,
  s.has_toilets,
  s.has_drinking_water,
  s.has_parking,
  s.has_changing_rooms,
  s.good_for_solo,
  s.good_for_pickup,
  s.good_for_training,
  s.beginner_friendly,
  s.notes,
  s.photo_asset_name,
  s.photo_url,
  s.osm_type,
  s.osm_id,
  s.osm_ref,
  s.osm_tags_json,
  s.import_batch
from deduped_staging s
where not exists (
    select 1
    from public.courts c
    where c.id = s.id
  )
  and not exists (
    select 1
    from public.courts c
    where c.country_code = s.country_code
      and c.location is not null
      and extensions.st_dwithin(
        c.location,
        extensions.st_setsrid(extensions.st_makepoint(s.longitude, s.latitude), 4326)::extensions.geography,
        30
      )
  );

-- Check final country coverage.
select
  country_code,
  count(*) as courts
from public.courts
group by country_code
order by country_code;
